### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'L2Weth.json'

### ISSUE THREAD

**Issue by ccx997t** [emilianobonassi/zksync-era#1]
hello,I  download  your project and run git clone https://github.com/emilianobonassi/zksync-era  , run 'zk init',  I got error。
Error: ENOENT: no such file or directory, open '/mnt/volume_nyc1_02/zksync-era1/contracts/zksync/artifacts-zk/cache-zk/solpp-generated-contracts/bridge//L2Weth.sol/L2Weth.json'

<img width="1254" alt="image" src="https://github.com/emilianobonassi/zksync-era/assets/38490332/323abe14-7a46-4f93-ae8b-093e38cd40d3">

**Comment by emilianobonassi** [comment]
Thanks @ccx997t for reporting

Please try the branch [l2weth-naming](https://github.com/emilianobonassi/zksync-era/tree/fix/l2weth-naming)

```
git fetch -p
git checkout origin/fix/l2weth-naming
rm -fr contracts/zksync/artifacts-zk contracts/zksync/cache-zk #clean cache
zk init
```

Please confirm that's working, so we can merge then https://github.com/emilianobonassi/zksync-era/pull/2

**Comment by emilianobonassi** [comment]
solved
